[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.crm.extensions.videoconferencing"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["video conferencing", "API integration", "customer data", "meeting management", "automation", "Vendor/HubSpot", "Area/CRM", "Type/Connector"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.extensions.videoconferencing"

[build-options]
observabilityIncluded = true
