[package]
distribution = "2201.11.0"
org = "ballerinax"
name = "hubspot.crm.extensions.videoconferencing"
version = "1.0.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
# icon = "icon.png" # TODO: update icon.png
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.crm.extensions.videoconferencing"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
